# Goal - I have to lint, build, test the code for frontend and backend
# Then push the images to dockerhub

name: CI

on:
    push:
        branches: [advanced]

jobs:
    frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Use Node.js 
              uses: actions/setup-node@v6
              with:
                node-version: "20"
                cache: 'npm' # Automates package caching for faster subsequent runs 
                cache-dependency-path: 'frontend/package-lock.json'

            - name: Install npm packages
              run: npm --prefix frontend/package.json install

            - name: Run linter 
              run: npm run lint

            - name: Run Tests
              run: npm run test


    
    #backend: 
