# Goal - To Run End to End DevSecOps CI Pipeline

name: DevSecOps

on:
    push:
        branches: [master]

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    dependency-checks:
        uses: ./.github/workflows/dependency-scan.yml

    docker-checks:
        uses: ./.github/workflows/docker-scans.yml